// export const GET_ALL_ACCESSORIES = 'GET_ALL_ACCESSORIES';
// export const GET_ALL_TSHIRTS = 'GET_ALL_TSHIRTS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_ID = 'GET_ALL_PRODUCTS_ID';
export const GET_ALL_PRODUCTS_NAME = 'GET_ALL_PRODUCTS_NAME'
export const POST_NEW_PRODUCTS = "POST_NEW_PRODUCTS"
export const SET_FILTERED_PRODUCTS =  'SET_FILTERED_PRODUCTS'
export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const UPDATE_USER = "UPDATE_USER"
export const SEARCH_USER = "SEARCH_USER"
export const GET_ALL_USERS = "GET_ALL_USERS"
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_BANNED_PRODUCT = "SET_BANNED_PRODUCT"
export const SET_FEATURED_PRODUCT = "SET_FEATURED_PRODUCT"
export const SET_PRIVILEGE_USER = "SET_PRIVILEGE_USER"
export const SET_STATUS_USER = "SET_STATUS_USER"
export const UPDATE_ADDRESS = "UPDATE_ADDRESS"
export const GET_ALL_BILLS = "GET_ALL_BILLS"
export const CREATE_NEW_REVIEWS = "CREATE_NEW_REVIEWS"
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS"
export const UPDATE_STOCK = "UPDATE_STOCK"
export const SET_ACTIVE_BILLS = 'SET_ACTIVE_BILLS'


