// export const GET_ALL_ACCESSORIES = 'GET_ALL_ACCESSORIES';
// export const GET_ALL_TSHIRTS = 'GET_ALL_TSHIRTS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_ID = 'GET_ALL_PRODUCTS_ID';
export const GET_ALL_PRODUCTS_NAME = 'GET_ALL_PRODUCTS_NAME'
export const POST_NEW_PRODUCTS = "POST_NEW_PRODUCTS"
export const SET_FILTERED_PRODUCTS =  'SET_FILTERED_PRODUCTS'

